name: Build MIPS Python Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup wheels folder
        run: |
          sudo mkdir -p /mnt/mipsel-root/root/wheels
          sudo chmod -R a+rX /mnt/mipsel-root/root/wheels
          sudo chown -R $USER:$USER /mnt/mipsel-root/root/wheels
          ls -la /mnt/mipsel-root/root/wheels/

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qemu-user-static \
            binfmt-support \
            debootstrap \
            systemd \
            procps \
            iproute2

      - name: Make scripts executable
        run: |
          chmod +x make-scripts-executable.sh
          ./make-scripts-executable.sh

      - name: Cache chroot and builder setup
        id: cache-setup
        uses: actions/cache@v4
        with:
          path: /tmp/mips-klipper-cache
          key: mips-setup-${{ hashFiles('scripts/chroot-setup.sh', 'scripts/builder-setup.sh') }}
          restore-keys: |
            mips-setup-

      - name: Setup MIPS build environment with caching
        run: sudo ./scripts/cache-helper.sh full-setup

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Build Shaketune wheels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sudo -E ./scripts/shaketune-build.sh

      - name: Build Klipper wheels
        run: sudo ./scripts/klipper-build.sh

      - name: Build Moonraker wheels
        run: sudo ./scripts/moonraker-build.sh

      
      - name: Upload wheels artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mipsel-python-wheels
          path: /mnt/mipsel-root/root/wheels/
          if-no-files-found: error
          retention-days: 90

      - name: Prepare wheels for GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          sudo chmod -R a+rX /mnt/mipsel-root/root/wheels
          sudo chown -R $USER:$USER /mnt/mipsel-root/root/wheels
          ls -la /mnt/mipsel-root/root/wheels/
          # Create pages directory
          mkdir -p wheels-page
          # Copy wheels
          cp /mnt/mipsel-root/root/wheels/*.whl wheels-page/
          # Generate index
          chmod +x scripts/generate-index.sh
          ./scripts/generate-index.sh wheels-page

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: wheels-page
          target-folder: wheels
          clean: true

      - name: Cleanup
        if: always()
        run: |
          sudo umount -l /mnt/mipsel-root/proc || true
          sudo umount -l /mnt/mipsel-root/sys || true
          sudo umount -l /mnt/mipsel-root/dev || true
          sudo rm -rf /mnt/mipsel-root
